---
layout: post
title: "R-Hackathoning - The finisher's guide"
tags: [rstats, stats, programming]
bibliography: ~/Literature/Bibtex/jabref.bib
comments: true
---

```{r,include=FALSE,echo=FALSE,message=FALSE}
##If default fig.path, then set it.
if (knitr::opts_chunk$get("fig.path") == "figure/") {
  knitr::opts_knit$set( base.dir = '/Users/hoehle/Sandbox/Blog/')
  knitr::opts_chunk$set(fig.path="figure/source/2016-10-23-quantileCI/")
}
fullFigPath <- paste0(knitr::opts_knit$get("base.dir"),knitr::opts_chunk$get("fig.path"))
filePath <- "/Users/hoehle/Sandbox/Blog/figure/source/2016-10-23-quantileCI/"

knitr::opts_chunk$set(echo = TRUE,fig.width=8,fig.height=5,fig.cap='') # autodep=TRUE
options(width=90)
library("dplyr")
library("ggplot2")
library("tidyr")
library("methods")
theme_set(theme_bw())
```

## Abstract

We present experiences from organizing a small R hackathon aimed at
advancing knowledge and documentation of the R package `surveillance`.
The hackathon was piggybacked on a conference visited by current and
potential package users in the area of infectious disease
epidemiology.. The output of the hackathon can be found at
[https://surveillancer.github.io/tutorials/](https://surveillancer.github.io/tutorials/).

## Introduction

A **[hackathon](https://en.wikipedia.org/wiki/Hackathon)** is a
extreme-programming sprint-like event where people involved in
software development and beyond meet for a short period of time with
the purpose of collaboriative programming, typically in
**open-source**.  The word hackathon is a merger of **hack** and
**marathon**, where [*hacking*](http://www.dictionary.com/browse/hack)
is to be understood as the skilfull modification of computer programs
(and not the malicious circumvention of security measures). Lots of good
guides have been written on
[how to run a successful Hackathon](https://hackathon.guide/).
In our area of application **infectious disease
epidemiology** - the standard for hackathons are the
[hackout](https://sites.google.com/site/hackoutwiki/home),
[hackout2](https://sites.google.com/site/hackout2/),
[hackout3](http://hackout3.ropensci.org/) events organized
by [Thibaut Jombart](http://www.imperial.ac.uk/people/t.jombart).

This blog post reports our experiences from organising a small **4x3
hackathon** (4 people, 3 days) for the surveillance R-package in
connection with the
[ESCAIDE2016](http://ecdc.europa.eu/en/escaide/Pages/ESCAIDE.aspx)
conference.

## Organizing and Running the Hackathon

### Why?

Over the last several years we worked on a package for the
visualization, modelling and monitoring of routine collected
surveillance time series. As most of us are busy with other tasks now,
it felt like a good idea to meet in person to work a little on the
package and network with potential users in order to increase
awareness of the package. The 10'th European Scientific Conference on
Applied Infectious Disease Epidemiology
([ESCAIDE2016](http://ecdc.europa.eu/en/escaide/Pages/ESCAIDE.aspx))
organized by the
[European Centre for Disease Prevention and Control](http://ecdc.europa.eu)
in Stockholm 28-30 Nov 2016 in Stockholm Sweden with its about 600
participants, felt like the right place to be.

### A Cool Name?

Stockholm is placed on the 59th parallel north, hence, during November
daylight is limited to about
[6:30 hours](http://www.timeanddate.com/sun/sweden/stockholm). In
other words: Perfect hacking conditions and to honour this **Hack in
the Dark** became our internal handle for the hackathon.

### What to do?
We started about 8 weeks before the hackathon to brainstorm using
[slack](https://slack.com/) as a messaging system. We then
created a priority matrix in [google docs](http://docs.google.com)
allowing each of the participants to prioritize the ideas. This gave
us an initial idea of what we wanted to do. Unfortunately, most of us
then got pretty busy with other activities so we never managed to
revisit the matrix until a couple of days before the start of the
hackathon and recapitulated matters in an "indian buffet process"
meeting in Stockholm at the night before the hackathon:

1. Write a couple of i/o tutorials promoting how to get data into the
package format and use various package functions on them
2. Use Open European Data for the tutorials - the theme of the
   ESCAIDE2016 conference was after all: **Data for action**
3. Make a shiny app to visualize the effect of chosing various
   parameters choices for the surveillance algorithms. The best choice
   of configuration parameters has been the main question throughout
   the years and unfortunately, the answer is mostly: it depends...
4. Demo twitter surveillance by monitoring the conference hashtag.

### Venue?

Piggybacking on an existing conference in a conference centre meant we
had to worry little about WLAN, food and seating.

### Source Code Management

We chose to create an organization **surveillancer** on
[github](http://www.github.com), which we then all joined with our
individual github accounts. All new projects were then conducted by
initiating new repositories.  The `surveillance` package itself is
still developed on [R-Forge](http://www.r-forge.r-project.org) using
`svn`, but since we knew most of our work would be *using* the package
and less *developing* the package, we decided to keep the existing
infrastructure for the package and develop the planned tutorials and
visualizations in a new github project. This worked ok, but switching
between `svn` and `git` for commits on different projects was not
always helpful: `git commit -a` is a useful friend if you don't know
the git staging area...

### Project Output Format?
We decided to use an R package structure together with
[pkgdown](https://hadley.github.io/pkgdown/) in order to create a
website containing all hackathon output. The tutorials were then
created as vignettes of this package - an immediate consequence of
having this on github was that all code was then directly available
for the interested user.

### Demo, demo, demo!

Inspired by the extreme programming paradigm and because we wanted to
interact with the conference, we decided to demo at least once a day
by posting some output of the hackathon on twitter. Besides the
outgoing publicity we also frequently demo'ed internally in order to
get input and suggestions. This worked pretty well - there is nothing
as motivating as getting input and suggestions frequently!

Interaction with the other conference participants was only
moderate. In hindsights we maybe should have aimed for a poster
presentation or a related activitity in order to generate a more IRL
awareness at the hackathon outside the virtual world of twitter.

## Summary

Altogether, the three days passed quickly and we managed to get the
four formulated goals of the hackathon done. Such intense software
sprints are hard work, so towards the end the motivation and
concentration decreased slightly. However, phases of intense coding
are perfectly supplemented by listening to scientifc talks to boost
motivation, talk to former colleagues or share the passion of R with
others working in the field.

* Advertisement: RECON. More R in the field.

Thus, it is important to have breaks
from being a team, focus on social aspects and do not ignore fresh air
& sunlight completely. Actually, to our surprise the 6:30 hours of
daylight were actually quite sunny in Stockholm!

* Recommendation: Put a code session as part of conferences. The
  hacking session?

The output of our hackathon can be found here:

<center>
[https://surveillancer.github.io/tutorials/](https://surveillancer.github.io/tutorials/)
</center>
<p>
As an appetizer to actually check out the site, here are two of our
tweets:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">First draft output of the <a href="https://twitter.com/hashtag/ESCAIDE2016?src=hash">#ESCAIDE2016</a> surveillance <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a> hackathon: Visualizing <a href="https://twitter.com/hashtag/opendata?src=hash">#opendata</a> by <a href="https://twitter.com/ECDC_EU">@ECDC_EU</a> on Salmonella Agona. <a href="https://twitter.com/hashtag/data4action?src=hash">#data4action</a> <a href="https://t.co/8ApaDNF07L">pic.twitter.com/8ApaDNF07L</a></p>&mdash; Michael Höhle (\@m_hoehle) <a href="https://twitter.com/m_hoehle/status/803270577150631937">November 28, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Interactive illustration of monitoring algorithms for infectious disease surveillance <a href="https://twitter.com/hashtag/escaide2016?src=hash">#escaide2016</a> <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a> <a href="https://t.co/qizcqqMbEJ">https://t.co/qizcqqMbEJ</a> <a href="https://t.co/LyZujDLsF2">pic.twitter.com/LyZujDLsF2</a></p>&mdash; Dirk Schumacher (\@dirk_sch) <a href="https://twitter.com/dirk_sch/status/803573405660286976">November 29, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>


## Acknowledgements

Thanks to [Maëlle Salmon](http://www.masalmon.eu/),
[Dirk Schumacher](https://www.dirk-schumacher.net/) and
[Sebastian Meyer](http://www.imbe.med.uni-erlangen.de/cms/sebastian_meyer.html)
for all their great work and the creative atmosphere during the
hackathon! The event was implicitly supported by the Swedish Research
Council as part of the project Statistical Modelling, Monitoring and
Predictive Analytics against Infectious Disease Outbreaks (grant
number 2015-05182_VR).


